### ISSUE TITLE
Latest Update broke source select

### ISSUE THREAD

**Issue by MrC001** [Tikipeter/repository.tikipeter#358]
Error when want list of sources.  Wiped and redid all settings...same error. (uninstall -- reinstall -- same error)

**Comment by MrC001** [comment]
[fenomscrapers.log](https://github.com/Tikipeter/repository.tikipeter/files/5820784/fenomscrapers.log)
Only log file I could find....

**Comment by baltzis** [comment]
I confirm the problem on both my TV box and desktop (win10). Attaching log. An error occurs when trying to display the sources list, after searching, for both TV series and films.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5821577/kodi.log)

**Comment by chrisnikol** [comment]
I have the same issue. At the log file say something about a miising xml file for window is missing

I think this is the relative part of the log file.

Is from the normal log file and not by setting the kodi log function at debug state but i think this is eniugh. In case that it isnt no problem to send and debug log.

---------------------------------------------------
2021-01-15 18:14:32.635 T:7496   ERROR: EXCEPTION: XML File for Window is missing
2021-01-15 18:14:32.636 T:7496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 5, in <module>
                                                routing(argv[2])
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 111, in routing
                                                Sources().playback_prep(params)
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 84, in playback_prep
                                                self.get_sources()
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 105, in get_sources
                                                self.play_source()
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 268, in play_source
                                                return self.display_results()
                                              File "C:\Users\chris\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 375, in display_results
                                                meta=meta, scraper_settings=self.scraper_settings, prescrape=self.prescrape)
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--
---------------------------------------------------------------------------------------------------------------

Of course as always i am gratefull to you for  your amazing addon.

**Comment by Tikipeter** [comment]
Until I can get home to fix this, you can download the latest script.module.tikiskins from this repo and install and that will fix the issue.

It hasn't updated with the recent Fen update like it should have.

**Comment by xyzfre** [comment]
> Until I can get home to fix this, you can download the latest script.module.tikiskins from this repo and install and that will fix the issue.
> 
> It hasn't updated with the recent Fen update like it should have.

Thank you so much for your response I did the update like you said and it’s working again,, Fen is a amazing add-on on my end it’s the best thank you for your GREAT work

**Comment by MrC001** [comment]
I did tikiskins update as well, no error anymore but doesn't list
anything.....

**Comment by MrC001** [comment]
Changed list display style....worked fine...just discovered this addon
again...great work.....

**Comment by Tikipeter** [comment]
Re-set Settings->Results->"Source Select" (or something like that).

**Comment by Tikipeter** [comment]
Should be fixed when the update I just uploaded goes through.
Someone please let me know if they get an update for all three modules `plugin.video.fen, plugin.module.tikiskins & script.tiki.artwork`.
Thanks all and apologies.

**Comment by xyzfre** [comment]
If we updated earlier like you said the script.module.tikiskins should we still see another update for tikiskins

**Comment by Tikipeter** [comment]
You should, yes. Because I raised the version number.

**Comment by Tikipeter** [comment]
There still might be an issue.......

**Comment by Tikipeter** [comment]
Yep. There was an extra `-` in the Fen version I uploaded's name. Bloody hell!
Fixing now...

**Comment by xyzfre** [comment]
> Should be fixed when the update I just uploaded goes through.
> Someone please let me know if they get an update for all three modules `plugin.video.fen, plugin.module.tikiskins & script.tiki.artwork`.
> Thanks all and apologies.

Yep all three modules updated everything seems to be working GREAT Thank you for your AMAZING  work love FEN 🙌🏼

**Comment by sblair77** [comment]
I uninstalled and reinstalled because updating wasn't pulling the new version "c" but I'm still getting the error.

😟 I've read through this issue and the tips/help in fen and I don't think I'm missing any steps. Is there something I should do after updating?

I cleared all settings and cache and restarted my modem. 🤷🏼‍♀️

**Comment by cgcgcgcgcg** [comment]
> I uninstalled and reinstalled because updating wasn't pulling the new version "c" but I'm still getting the error.
> 
> worried I've read through this issue and the tips/help in fen and I don't think I'm missing any steps. Is there something I should do after updating?
> 
> I cleared all settings and cache and restarted my modem. 🤷🏼‍♀️

Same here.
I updated to v1.8.25c issue insisted. Uninstalled, then reinstalled Fen, still getting the error.

**Comment by baltzis** [comment]
**On both TV Box and Desktop computer (win 10):**
I just updated to FEN 1.8.25c and the issues persist. However, after manually installing _script.module.tikiskins_ 1.0.03b, the sources list is displayed as usual. It seems that updating to1.8.25c, does not up update _script.module.tikiskins_.

**Comment by Tikipeter** [comment]
>manually installing script.module.tikiskins 1.0.03b

That might need to be the way to go, then. After the error I made originally, sometimes Kodi's repo management get's stuffed and it simply won't do what it's supposed to.

I'd install `plugin.module.tikiskins & script.tiki.artwork` (latest versions) from here within the repo. Hopefully that will fix things moving forward. If correct, you should see them both in the "Manage dependencies" section of Kodi.

**Comment by cgcgcgcgcg** [comment]
@Tikipeter, 

https://user-images.githubusercontent.com/38960370/104811966-acad8380-5807-11eb-8e86-43767da1bf4b.mp4

I just did that on my build and worked -I restarted the build after installing Fen and the dependencies, but had to Clear Scrapers Cache to get sources after restarting.
Here's a video that might help.

**Comment by sblair77** [comment]
> @Tikipeter,
> 
>  Fen.update.mp4 
> I just did that on my build and worked -I restarted the build after installing Fen and the dependencies, but had to Clear Scrapers Cache to get sources after restarting.
> Here's a video that might help.

Wow thanks for that! Do you know how to do it from within Kodi? I'm not sure how to get to where you are.

**Comment by cgcgcgcgcg** [comment]
> > @Tikipeter,
> > Fen.update.mp4
> > I just did that on my build and worked -I restarted the build after installing Fen and the dependencies, but had to Clear Scrapers Cache to get sources after restarting.
> > Here's a video that might help.
> 
> Wow thanks for that! Do you know how to do it from within Kodi? I'm not sure how to get to where you are.

The fastest way is to click on (Settings >) Addons > Search, and type Fen.

**Comment by sblair77** [comment]
> > > @Tikipeter,
> > > Fen.update.mp4
> > > I just did that on my build and worked -I restarted the build after installing Fen and the dependencies, but had to Clear Scrapers Cache to get sources after restarting.
> > > Here's a video that might help.
> > 
> > 
> > Wow thanks for that! Do you know how to do it from within Kodi? I'm not sure how to get to where you are.
> 
> The fastest way is to click on (Settings >) Add-ons > Search, and type Fen.

You guys rock!

**Comment by streamindemons** [comment]
I wanted to mention I'm experiencing the same thing, followed the video and sources are found but no links are actually showing. Have tikiskins 1.0.03b and FEN 1.8.25c. Basically the window that should be displaying the links is just blank, with the art of the media in the background.
![IMG_20210119_090223](https://user-images.githubusercontent.com/71285381/105044808-25ddee00-5a35-11eb-8f60-834c3d55f7c9.jpg)
